spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/cgcoffee"
    username: "root"
    password: "0420"
  jpa:
    hibernate:
      ddl-auto: create
